<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Herald.Sinks.Sqs.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>HERALD004;xUnit1031</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Herald.Sinks.Sqs\Herald.Sinks.Sqs.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\_shared\*.cs" LinkBase="_CoreTestHelpers" />
  </ItemGroup>
</Project>
